# Generated by Django 4.2.7 on 2024-01-31 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_alter_product_active_alter_product_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CATparent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATparent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Parent'),
        ),
    ]
