# Generated by Django 4.2.7 on 2024-01-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CATparent',
        ),
    ]
