# Generated by Django 4.2.7 on 2024-01-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_category_catparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catslug',
            field=models.SlugField(default=1, max_length=200, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='catname',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
