# Generated by Django 4.2.7 on 2024-01-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_category_catslug_alter_category_catname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catslug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='slug'),
        ),
    ]
