# Generated by Django 4.2.7 on 2024-02-12 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_product_date_alter_review_revproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 7, 54, 51, 301285)),
        ),
        migrations.AlterField(
            model_name='review',
            name='RevProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.product'),
        ),
    ]
