# Generated by Django 4.2.7 on 2024-02-13 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_review_options_rename_text_review_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 4, 58, 49, 65170)),
        ),
    ]
